server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/secret?characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:dao/*